server:
  port: 82
spring:
  application:
    name: cloud-order-service-hystrix


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

#Feign超时配置
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
